on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: |
          echo "Hello from Flicks Nation!"
          echo "Your satisfaction our pride"
          echo "The world at your finger tip with flicks"
          echo "Live your life at your own risk!!"
      
